// Generated by gencpp from file custom_srv_service/custom_srv.msg
// DO NOT EDIT!


#ifndef CUSTOM_SRV_SERVICE_MESSAGE_CUSTOM_SRV_H
#define CUSTOM_SRV_SERVICE_MESSAGE_CUSTOM_SRV_H

#include <ros/service_traits.h>


#include <custom_srv_service/custom_srvRequest.h>
#include <custom_srv_service/custom_srvResponse.h>


namespace custom_srv_service
{

struct custom_srv
{

typedef custom_srvRequest Request;
typedef custom_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct custom_srv
} // namespace custom_srv_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_srv_service::custom_srv > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::custom_srv_service::custom_srv&) { return value(); }
};

template<>
struct DataType< ::custom_srv_service::custom_srv > {
  static const char* value()
  {
    return "custom_srv_service/custom_srv";
  }

  static const char* value(const ::custom_srv_service::custom_srv&) { return value(); }
};


// service_traits::MD5Sum< ::custom_srv_service::custom_srvRequest> should match 
// service_traits::MD5Sum< ::custom_srv_service::custom_srv > 
template<>
struct MD5Sum< ::custom_srv_service::custom_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_srv_service::custom_srv >::value();
  }
  static const char* value(const ::custom_srv_service::custom_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_srv_service::custom_srvRequest> should match 
// service_traits::DataType< ::custom_srv_service::custom_srv > 
template<>
struct DataType< ::custom_srv_service::custom_srvRequest>
{
  static const char* value()
  {
    return DataType< ::custom_srv_service::custom_srv >::value();
  }
  static const char* value(const ::custom_srv_service::custom_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_srv_service::custom_srvResponse> should match 
// service_traits::MD5Sum< ::custom_srv_service::custom_srv > 
template<>
struct MD5Sum< ::custom_srv_service::custom_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_srv_service::custom_srv >::value();
  }
  static const char* value(const ::custom_srv_service::custom_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_srv_service::custom_srvResponse> should match 
// service_traits::DataType< ::custom_srv_service::custom_srv > 
template<>
struct DataType< ::custom_srv_service::custom_srvResponse>
{
  static const char* value()
  {
    return DataType< ::custom_srv_service::custom_srv >::value();
  }
  static const char* value(const ::custom_srv_service::custom_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SRV_SERVICE_MESSAGE_CUSTOM_SRV_H
