set(_CATKIN_CURRENT_PACKAGE "webots_simulation")
set(webots_simulation_VERSION "0.0.0")
set(webots_simulation_MAINTAINER "kun <kun@todo.todo>")
set(webots_simulation_PACKAGE_FORMAT "2")
set(webots_simulation_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "single_leg_test")
set(webots_simulation_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "single_leg_test")
set(webots_simulation_BUILDTOOL_DEPENDS "catkin")
set(webots_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(webots_simulation_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "single_leg_test")
set(webots_simulation_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "single_leg_test")
set(webots_simulation_TEST_DEPENDS )
set(webots_simulation_DOC_DEPENDS )
set(webots_simulation_URL_WEBSITE "")
set(webots_simulation_URL_BUGTRACKER "")
set(webots_simulation_URL_REPOSITORY "")
set(webots_simulation_DEPRECATED "")