set(_CATKIN_CURRENT_PACKAGE "single_leg_test")
set(single_leg_test_VERSION "0.0.0")
set(single_leg_test_MAINTAINER "kun <kun@todo.todo>")
set(single_leg_test_PACKAGE_FORMAT "2")
set(single_leg_test_BUILD_DEPENDS "roscpp" "geometry_msgs")
set(single_leg_test_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs")
set(single_leg_test_BUILDTOOL_DEPENDS "catkin")
set(single_leg_test_BUILDTOOL_EXPORT_DEPENDS )
set(single_leg_test_EXEC_DEPENDS "roscpp" "geometry_msgs")
set(single_leg_test_RUN_DEPENDS "roscpp" "geometry_msgs")
set(single_leg_test_TEST_DEPENDS )
set(single_leg_test_DOC_DEPENDS )
set(single_leg_test_URL_WEBSITE "")
set(single_leg_test_URL_BUGTRACKER "")
set(single_leg_test_URL_REPOSITORY "")
set(single_leg_test_DEPRECATED "")