set(_CATKIN_CURRENT_PACKAGE "test_msg")
set(test_msg_VERSION "0.0.0")
set(test_msg_MAINTAINER "kun <kun@todo.todo>")
set(test_msg_PACKAGE_FORMAT "2")
set(test_msg_BUILD_DEPENDS "message_generation" "roscpp")
set(test_msg_BUILD_EXPORT_DEPENDS )
set(test_msg_BUILDTOOL_DEPENDS "catkin")
set(test_msg_BUILDTOOL_EXPORT_DEPENDS )
set(test_msg_EXEC_DEPENDS "message_runtime" "roscpp")
set(test_msg_RUN_DEPENDS "message_runtime" "roscpp")
set(test_msg_TEST_DEPENDS )
set(test_msg_DOC_DEPENDS )
set(test_msg_URL_WEBSITE "")
set(test_msg_URL_BUGTRACKER "")
set(test_msg_URL_REPOSITORY "")
set(test_msg_DEPRECATED "")